title: Mairon
description: > # this means to ignore newlines until "baseurl:"
  Personal page of Mairon.
permalink: ':title/'
#baseurl: "/mahzoun.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Mairon # add your name
author-img: mahzoun.jpg # add your photo
about-author: I am Mairon (Officially, Mohammad Mahzoun). I am from Bojnord, Iran.  I am a PhD student at TU/e working on theoretical foundations of security. I am also a newbie photographer. I care about mother nature, kids, and arts. Feel free to get in touch!
social-twitter: mmahzoun # add your Twitter handle
social-facebook: mmahzoun # add your Facebook handle
social-github: mahzoun # add your Github handle
social-linkedin: mmahzoun # add your Linkedin handle
social-email: Mohammad.Mahzoun@gmail.com # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
